# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4191a5f9d000c9d522d9ec83e990a455b0e679d53f9a4e647fc65406d726cd49ad425c557da3f44254f04524c76152f636e74fb8a1e64cbfe2335c5f9045028

test:
  secret_key_base: c7e0a480609e44191108f335a0cae63f1948622093f002c528a13baa9fdcb27a3767b7c0d822a8316efba6b43be08336164e4b4bdb324cc8ecf601af160e0236

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
